spring:
  datasource:
    url: jdbc:mysql://localhost:3306/teach?useSSL=false&serverTimezone=UTC
    username: root
    password: 15930972507147x
    driver-class-name: com.mysql.cj.jdbc.Driver


  security:
    enabled: false
